name: backup for gitee.com/no-mystery/shuyuan
on:
  schedule:
    - cron: 0 * * * *
  #push:
  #  branches:
  #    - "master"
jobs:
  build:
    name: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Merge shuyuan source
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git remote add bushixuanqi https://gitee.com/no-mystery/shuyuan.git
          git fetch bushixuanqi
          git checkout -b master1 bushixuanqi/master
          git checkout master
          git merge master1 --allow-unrelated-histories --no-commit
          git branch -d master1
          git remote remove bushixuanqi
          rm -f ./.git/MERGE_MSG

      - name: Git push assets to "master" branch
        run: |
          git remote set-url --add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/${{ secrets.CODING_NAME }}/shuyuan/shuyuan.git"
          git fetch --unshallow origin
          git push -u origin master
